name: color_generator
description: Color Generator
publish_to: none

version: 0.1.0

# Flutter SDK releases: https://docs.flutter.dev/development/tools/sdk/releases
environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ^3.7.7

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  

dev_dependencies:
  flutter_lints: ^2.0.0
  solid_lints: ^0.0.16
  

flutter:
  uses-material-design: true
